[Settings]
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=Papirus-Dark
gtk-font-name=JetBrains Mono 11
#gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=1

# Thunar specific settings.
gtk-recent-files-enabled=0
gtk-recent-files-limit=0
gtk-recent-files-max-age=0
