# yt-dlp configuration file

# General Options
--no-mtime
--restrict-filenames
--embed-thumbnail
--embed-chapters

# Subtitles
--sub-langs "en-US|en"
--embed-subs
--convert-subs srt
--prefer-free-formats

# Video Format Options
-f 'bestvideo[height<=?1080]+bestaudio/best' # <= 1080p
--merge-output-format mkv

# Download Directory
#-o '~/Downloads/%(title)s.%(ext)s'
-o '%(title)s.%(ext)s'

# Network Options
--socket-timeout 30
--retries 25
--fragment-retries 25
--no-check-certificate

# Cookies
--cookies-from-browser firefox

# Additional Option

# Authentication (if needed)
# --username YOUR_USERNAME
# --password YOUR_PASSWORD

# Proxy Settings (if needed)
# --proxy PROXY_URL

# Proxy Example: yt-video-download --proxy 'socks5://167.71.100.174:1080' 'https://www.youtube.com/watch?v=EEvXPJ97Q04'
